SK.define('App.Test2',{ 
    extend:'App.Test',
    init:function(){
        this.callParent()
    },
    constructor:function(config){
        this.console(this.a);
        this.callParent(config);
        this.console(this.a);
    }
})