SK.define('App.Test2',{ 
    extend:'App.Test',
    init:function(){
        this.callParent()
    },
    constructor:function(config){
        console.log(1);
        this.callParent(config);
        console.log(this.a);
    }
})